# AED

In [2]:
from export import Config
c = Config(source_path='C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments')

In [ ]:
from preprocess import df_anova
import yaml

def ARGS_ANOVA_TABLE():
    with open(r"C:\Users\samue\OneDrive\Escritorio\Tareas UNI\tfg\tfg_samuel\vis\analysis\config_files\parameters.yml", "r") as file:
        pams = yaml.load(file, Loader=yaml.SafeLoader)
    return pams["anova"]["anova"]

{'anova': {'factor1': ['algorithm',
   'algorithm_rounds',
   'consensus_iterations',
   'training_epochs',
   'dataset',
   'distribution',
   'ann'],
  'factor2': ['algorithm',
   'algorithm_rounds',
   'consensus_iterations',
   'training_epochs',
   'dataset',
   'distribution',
   'ann'],
  'level': ['minimum_loss_achieved',
   'maximum_accuracy_achieved',
   'maximum_recall_achieved',
   'maximum_precision_achieved',
   'maximum_f1_achieved',
   'mean_seconds_by_round']}}

In [1]:
from preprocess import create_nodes_df

df = create_nodes_df()
df

,log_timestamp,log_name,algorithm_round,timestamp,agent,seconds_to_complete,epoch,accuracy,loss,precision,recall,f1_score
0,2025-03-29 19:08:27.294,rf.nn.train.agent.a0,1,2025-03-29T18:08:24.989248Z,a0,2.288031,1,0.563326,1.027085,0.350174,0.329411,0.323738
1,2025-03-29 19:08:28.920,rf.nn.train.agent.a0,1,2025-03-29T18:08:27.297533Z,a0,1.599896,2,0.664387,0.815752,0.613345,0.496803,0.507530
2,2025-03-29 19:08:30.600,rf.nn.train.agent.a0,1,2025-03-29T18:08:28.920351Z,a0,1.660380,3,0.710344,0.714695,0.653805,0.553718,0.573970
3,2025-03-29 19:08:32.137,rf.nn.train.agent.a1,1,2025-03-29T18:08:31.658622Z,a1,0.478978,1,0.879403,0.432627,0.230675,0.166214,0.175038
4,2025-03-29 19:08:32.527,rf.nn.train.agent.a1,1,2025-03-29T18:08:32.158209Z,a1,0.359516,2,0.925970,0.270213,0.351141,0.314946,0.329106
...,...,...,...,...,...,...,...,...,...,...,...,...
1645,2025-03-29 20:24:25.446,rf.nn.train.agent.a1,110,2025-03-29T19:24:24.175841Z,a1,1.264589,2,0.999403,0.000707,0.832868,0.832811,0.832839
1646,2025-03-29 20:24:26.703,rf.nn.train.agent.a1,110,2025-03-29T19:24:25.446945Z,a1,1.249980,3,1.000000,0.000348,1.000000,1.000000,1.000000
1647,2025-03-29 20:24:33.987,rf.nn.train.agent.a0,110,2025-03-29T19:24:30.066878Z,a0,3.890157,1,0.998694,0.003688,0.554031,0.555006,0.554516
1648,2025-03-29 20:24:38.124,rf.nn.train.agent.a0,110,2025-03-29T19:24:33.989761Z,a0,4.109624,2,0.999539,0.001185,0.999581,0.999579,0.999580
1649,2025-03-29 20:24:42.716,rf.nn.train.agent.a0,110,2025-03-29T19:24:38.128858Z,a0,4.558109,3,0.999769,0.001079,0.999626,0.999735,0.999681

In [5]:
nodes = (
        df.groupby(["agent", "timestamp"])["accuracy"].max().reset_index()
    )
nodes

     agent                    timestamp  accuracy
0       a0  2025-03-29T18:08:24.989248Z  0.563326
1       a0  2025-03-29T18:08:27.297533Z  0.664387
2       a0  2025-03-29T18:08:28.920351Z  0.710344
3       a0  2025-03-29T18:09:04.257472Z  0.683753
4       a0  2025-03-29T18:09:06.027423Z  0.745005
...    ...                          ...       ...
1645    a4  2025-03-29T19:22:43.775138Z  1.000000
1646    a4  2025-03-29T19:22:44.388061Z  1.000000
1647    a4  2025-03-29T19:23:48.314472Z  0.997034
1648    a4  2025-03-29T19:23:48.776833Z  1.000000
1649    a4  2025-03-29T19:23:49.226913Z  1.000000

[1650 rows x 3 columns]

In [ ]:
from visualization.network import generate
figs = generate(config = Config(), action="")
fig.layout.sliders[0].update(active=145)
fig.write_image("network.svg")

TypeError: create_combined_plot() missing 5 required positional arguments: 'nodes_plot', 'edges_plot', 'x_coords', 'y_coords', and 'range_color'

In [ ]:
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("in")
parser.add_argument("out")
parser.add_argument("config")

args = parser.parse_args()
variables = vars(args)
print(variables)

In [ ]:
from pydantic import FilePath
from config import Config, download_figures
import anova
import algorithm
import data_split
import messages
import convergence
import inference
import network

async def analyze(input: FilePath, output: FilePath, config_file: FilePath) -> None:
    config = Config(source_path=input, output_path=output, plots=config_file)
    anova.generate(config=config, action="download")
    algorithm.generate(config=config, action="download")
    data_split.generate(config=config, action="download")
    messages.generate(config=config, action="download")
    convergence.generate(config=config, action="download")
    inference.generate(config=config, action="download")
    network.generate(config=config, action="download")
    
    # anova.generate(config=config, action="generate")
    # download_figures("svg", "anova", output)
    
analyze(input='C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments', output="images2", config_file="config.yaml")

1
1

WARNING	Thread(Thread-41 (run)) choreographer.browser_async:browser_async.py:_close()- Resorting to unclean kill browser.

1
1
1
1
1
1

WARNING	Thread(Thread-53 (run)) choreographer.browser_async:browser_async.py:_close()- Resorting to unclean kill browser.

1

TypeError: generate() got an unexpected keyword argument 'action'

# Algorithm

1. Violin plot
2. Ordered execution
3. Avance entre rondas por timestamp (Sin hacer)

In [34]:
import branca.colormap as cm
cmap = cm.linear.Pastel1_09.scale(0, len(agents)-1)
type(cmap)

branca.colormap.LinearColormap

In [ ]:
#1.
import pandas as pd
import plotly.express as pxs
import plotly.graph_objects as go
from pathlib import Path

a = Path(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw")

data = pd.read_csv(a / "algorithm.csv")
agents = list(map(lambda x: x.split("@")[0], sorted(data.agent.unique())))
times = []
for agent in agents:
    agent_data = data[(data.agent == agent + "@localhost")]
    time = list(agent_data.seconds_to_complete)
    times.append(time)

df_bolos = pd.DataFrame(columns=agents)
for t, a in zip(times, agents):
    df_bolos[a] = t
df_bolos = df_bolos.melt()
fig = go.Figure()
for agent in agents:
    fig.add_trace(
        go.Violin(
            x=df_bolos["variable"][df_bolos["variable"] == agent],
            y=df_bolos["value"][df_bolos["variable"] == agent],
            name=agent,
            box_visible=True,
            meanline_visible=True,
        )
    )
fig.update_layout(title_text="Seconds to complete training round by agent")

fig.update_layout(config["algorithm"]["violin"]["layout"])
fig.update_traces(config["algorithm"]["violin"]["traces"])
fig

In [51]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from more_itertools import sort_together

data = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/algorithm.csv")
data = data[data.algorithm_round <= 100]
data.timestamp = pd.to_datetime(data.timestamp)
agents = data.agent.unique()
times = []
elapsed = []
for i,agent in enumerate(agents):
    dates = list(data.timestamp[data.agent==agent])
    rang = dates[-1] - dates[0]
    times.append(rang.total_seconds())
    elapsed.append(dates[-1])

m = min(elapsed)
for i, agent in enumerate(agents):
    elapsed[i] = (elapsed[i] - m).total_seconds()
    
elapsed, agents, times  = sort_together((elapsed, agents, times))

df = pd.DataFrame({"seconds":times, "agents": list(map(lambda x: x.split("@")[0], agents)), "seconds elapsed": elapsed})
fig = px.bar(df, x='seconds elapsed', y='agents',
             hover_data=['seconds', 'seconds elapsed'], 
             color='agents',
             labels={'pop':'seconds'},
             text="seconds",
             title="Tiempos de ejecución ordenados por agente",
             orientation='h')
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig

In [5]:
filename = "fig.json"
a = Path(filename)
a.suffix

'.json'

In [8]:
from config import Config
import anova
config = Config()
anova.generate(config)

[['Figures', 'Created']]

In [55]:
import plotly.io as pio

with open(filename, 'r') as f:
    fig = pio.from_json(f.read())
fig

# Data split

1. Bubble plot for every stage (3)

In [2]:
import pandas as pd
import plotly.graph_objects as go
import numpy as np
import branca.colormap as cm
from matplotlib.colors import to_hex

data = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/data_split.csv")
agents = data.agent.unique()

cmaps = [cm.linear.Pastel1_03.scale(0, 2),
         cm.linear.Pastel1_04.scale(0, 3),
         cm.linear.Pastel1_05.scale(0, 4),
         cm.linear.Pastel1_06.scale(0, 5),
         cm.linear.Pastel1_07.scale(0, 6),
         cm.linear.Pastel1_08.scale(0, 7),
         cm.linear.Pastel1_09.scale(0, 8)]
dic_cmaps = {str(i+3):cmap for i,cmap in enumerate(cmaps)}
labels = data.label.unique()

try:
    cmap = dic_cmaps[str(len(labels))]
except KeyError:
    if len(labels) < 3:
        cmap = cm.linear.Pastel1_03.scale(0, len(labels)-1)
    else:
        cmap = cm.linear.Pastel1_09.scale(0, len(labels)-1)

colors = ["white"] + [cmap(i) for i in range(len(labels))] + ["white"]
colors = list(map(to_hex, colors))

figs = []
phases = ["train", "validation", "test"]
visible = True
for phase in phases:
    fig = go.Figure()
    labels = data.label.unique()
    X = np.zeros((len(labels) + 2, len(agents) + 2))
    for i, agent in enumerate(agents):
        split_data = data[(data.agent == agent) & (data.description == phase)]
        for x, (_, row) in enumerate(split_data.iterrows()):
            X[row.label + 1, i + 1] = row["count"]

    scale = 10
    M, N = X.shape
    X_sizes = X.copy()
    for i in range(M):
        xmin, xmax = X_sizes[i, :].min(), X_sizes[i, :].max()
        tmin, tmax = 20, 55
        X_sizes[i, :] = (X_sizes[i, :] - xmin) / (xmax - xmin) * (
            tmax - tmin
        ) + tmin
    x = []
    y = []
    colores = []
    sizes = []
    texts = []
    for j in range(N):
        for i in range(M):
            color = colors[i]
            if X[i, j] != 0:
                x.append(j)
                y.append(i)
                colores.append(color)
                sizes.append(X_sizes[i, j])
                texts.append(f"{int(X[i,j])}")
    fig.add_trace(
        go.Scatter(
            mode="markers+text",
            x=x,
            y=y,
            marker=dict(color=colores, size=sizes, opacity=1),
            text=texts,
            line=dict(color="black", width=1),
            visible=visible,
            hovertemplate="<br><b>Agent</b>: %{x}<br>"
            + "<br><b>Digit</b>: %{y}<br>"
            + "<br><b>Samples</b>: %{text}<br>",
        )
    )

    # Update the figure layout with the dropdown menu
    fig.update_layout(
        title_text=f"Categorical bubble plot for {phase}",
        xaxis_title="Agents",
        yaxis_title="Labels",
    )

    fig.update_layout(xaxis_range=[0, len(agents) + 1])
    fig.update_layout(yaxis_range=[0, len(colors) - 1])
    fig.update_layout(width=143 * (len(agents) + 2))
    fig.update_layout(height=67 * len(colors))
    fig.update_layout(plot_bgcolor="rgb(256,256,256)")
    fig.update_xaxes(
        ticktext=agents,
        tickvals=list(range(1, len(agents) + 1)),
        showgrid=True,
        gridwidth=1,
        gridcolor="grey",
    )
    fig.update_yaxes(
        ticktext=sorted(labels),
        tickvals=list(range(1, len(labels) + 1)),
        showgrid=True,
        gridwidth=1,
        gridcolor="grey",
    )
    figs.append(fig)
figs[0]

C:\Users\samue\AppData\Local\Temp\ipykernel_11056\2766508680.py:49: RuntimeWarning:

invalid value encountered in divide

In [ ]:
w, h = fig.layout.width, fig.layout.height
figs[0].write_image("image.svg", width=w, height=h)

# Message

1. Total mensajes entre agente
2. Tabla estadística tipos de mensajes
3. Distribución mensajes en el tiempo

In [149]:
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff

data = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/02_non_complete/raw/message.csv")
print(len(data))
data.sender = list(map(lambda x: x.split("@")[0], data.sender))
data.to = list(map(lambda x: x.split("@")[0], data.to))
df_cross = pd.crosstab(index=data.sender, columns=data.to)

agents = data.sender.unique()
fig = px.imshow(df_cross.to_numpy(), x=agents, y=agents, color_continuous_scale="Viridis", aspect="auto")
fig.update_traces(text=df_cross, texttemplate="<b>%{text}</b>")
fig.update_xaxes(side="top")
fig.update_layout(title_text="Total de mensajes enviados entre agentes")

1754

In [ ]:
data = data[["sender", "to", "size"]]
data.sender = list(map(lambda x: x.split("@")[0], data.sender))
data.to = list(map(lambda x: x.split("@")[0], data.to))
#data_coss = pd.crosstab(index=data.sender, columns=data.to, values=data.size)
data_cross = data.groupby(["sender", "to"])["size"].sum().div(1024*1024).round(0).unstack().fillna(0)
data_cross
agents = data.sender.unique()
fig = px.imshow(data_cross.to_numpy(), x=agents, y=agents, color_continuous_scale="Viridis", aspect="auto")
fig.update_traces(text=data_cross, texttemplate="<b>%{text}</b>")
fig.update_xaxes(side="top")
fig.update_layout(title_text="Tamaño de la información enviada entre agentes")

In [ ]:
data = data[["sender", "to", "size"]]
data.sender = list(map(lambda x: x.split("@")[0], data.sender))
data.to = list(map(lambda x: x.split("@")[0], data.to))
data_cross = pd.crosstab(index=data.sender, columns=data.to)
agents = data.sender.unique()
fig = px.imshow(data_cross.to_numpy(), x=agents, y=agents, color_continuous_scale="Viridis", aspect="auto")
fig.update_traces(text=data_cross, texttemplate="<b>%{text}</b>")
fig.update_xaxes(side="top")
fig.update_layout(title_text="Tamaño de la información enviada entre agentes")
fig

In [41]:
import plotly.figure_factory as ff
stats = data.groupby("type").agg(
    number_of_messages=('size', 'count'),
    total_size=('size', 'sum'),
    average_size=('size', 'mean'),
    standard_deviation=('size', 'std'),
    minimum_size=('size', 'min'),
    maximum_size=('size', 'max')
).reset_index().round(2)
ff.create_table(stats)

In [69]:
import plotly.express as px
data = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/message.csv")
data.timestamp = pd.to_datetime(data.timestamp)
min_date = data.timestamp.min()
data["timestamp_minutes"] = data.timestamp.apply(lambda x: int((x - min_date).total_seconds() / 60.0))
fig = px.histogram(data, x="timestamp_minutes")
fig.update_layout(title_text="Distribución de mensajes en el tiempo")
fig

In [40]:
import plotly.express as px
data = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/message.csv")
data.timestamp = pd.to_datetime(data.timestamp)
min_date = data.timestamp.min()
data["timestamp_minutes"] = data.timestamp.apply(lambda x: int((x - min_date).total_seconds() / 60.0))
fig = px.histogram(data, x="timestamp_minutes", color="type")
fig.update_layout(title_text="Distribución de mensajes en el tiempo por tipo")
fig

In [74]:
fig.data

(Histogram({
     'bingroup': 'x',
     'histfunc': 'sum',
     'hovertemplate': 'timestamp_minutes=%{x}<br>sum of size=%{y}<extra></extra>',
     'legendgroup': '',
     'marker': {'color': 'indianred', 'pattern': {'shape': ''}},
     'name': '',
     'orientation': 'v',
     'showlegend': False,
     'x': array([ 0,  0,  0, ..., 76, 76, 76], shape=(13185,)),
     'xaxis': 'x',
     'y': array([    443,     447,     446, ..., 4812703, 4812703, 4812703],
                shape=(13185,)),
     'yaxis': 'y'
 }),)

In [79]:
import plotly.express as px
data = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/message.csv")
data.timestamp = pd.to_datetime(data.timestamp)
min_date = data.timestamp.min()
data["timestamp_minutes"] = data.timestamp.apply(lambda x: int((x - min_date).total_seconds() / 60.0))

fig = px.histogram(data, x="timestamp_minutes", y="size", color_discrete_sequence=['indianred'])
fig.update_layout(title_text="Distribución de información en el tiempo")
fig.update_traces(marker_color="green")
fig

In [ ]:
import plotly.express as px
data = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/message.csv")
data.timestamp = pd.to_datetime(data.timestamp)
min_date = data.timestamp.min()
data["timestamp_minutes"] = data.timestamp.apply(lambda x: int((x - min_date).total_seconds() / 60.0))

fig = px.histogram(data, x="timestamp_minutes", y="size", color="type")
fig.update_layout(title_text="Distribución de información en el tiempo por tipo de mensaje")
fig

# Convergence

1. Layer evolution
2.

In [ ]:
import os
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from itertools import groupby
import numpy as np
from config import Config
config = Config()


df = pd.read_csv(config.experiment_path / r"nn_convergence.csv")
lst = df.layer.unique()
f = lambda x: x.split(".")[0]
# global layers_opts
layers_opts = {f(k): list(g) for k, g in groupby(sorted(lst, key=f), key=f)}
df = df[
    (df.description == "PRE-TRAIN")
    & (df.epoch_or_iteration == 1)
]
pivot = df.pivot(columns="layer", values="weight")
df = df[df.layer == layers_opts["conv1"][0]].reset_index()

for layer in layers_opts.keys():
    df[layers_opts[layer][0]] = (
        pivot[layers_opts[layer][0]]
        .dropna()
        .reset_index()[f"{layers_opts[layer][0]}"]
    )
    df[layers_opts[layer][1]] = (
        pivot[layers_opts[layer][1]]
        .dropna()
        .reset_index()[f"{layers_opts[layer][1]}"]
    )
global min_x
min_x = df[layers_opts["conv1"][0]].min()
global min_y
min_y = df[layers_opts["conv1"][1]].min()
global max_x
max_x = df[layers_opts["conv1"][0]].max()
global max_y
max_y = df[layers_opts["conv1"][1]].max()

df = df.sort_values(
    [
        "algorithm_round",
        "agent",
    ],
    ignore_index=True,
)
N_UNIQUE_AGENTS = df["agent"].nunique()
df_indexed = pd.DataFrame()
for index in np.arange(start=0, stop=len(df) + 1, step=N_UNIQUE_AGENTS):
    df_slicing = df.iloc[:index].copy()
    df_slicing["frame"] = index // N_UNIQUE_AGENTS
    df_indexed = pd.concat([df_indexed, df_slicing])
    
df

In [14]:
a = [5,6,7,8,9,10]
from tqdm import tqdm
import time
for i in tqdm(a, desc="Downloading figures"):
    time.sleep(1)
    print(i)

Downloading figures:  17%|█▋        | 1/6 [00:01<00:05,  1.00s/it]

5

Downloading figures:  33%|███▎      | 2/6 [00:02<00:04,  1.00s/it]

6

Downloading figures:  50%|█████     | 3/6 [00:03<00:03,  1.00s/it]

7

Downloading figures:  67%|██████▋   | 4/6 [00:04<00:02,  1.01s/it]

8

Downloading figures:  83%|████████▎ | 5/6 [00:05<00:01,  1.00s/it]

9

Downloading figures: 100%|██████████| 6/6 [00:06<00:00,  1.00s/it]

10

In [128]:
import pandas as pd

def myfunc(s):
    return np.mean(s)

df = pd.DataFrame({'category1':['a','a','a', 'b', 'b','b'],
  'category2':['a', 'b', 'a', 'b', 'a', 'b'],
  'var1':np.random.randint(0,100,6),
  'var2':np.random.randint(0,100,6)}
)

df = (df.set_index(["category1", "category2"])
         .assign(var3=df.groupby(["category1", "category2"]).var1.apply(myfunc))
         .reset_index()
      )
df

  category1 category2  var1  var2  var3
0         a         a    32    44  24.5
1         a         b    13    85  13.0
2         a         a    17    89  24.5
3         b         b    90    45  61.0
4         b         a    85    29  85.0
5         b         b    32    52  61.0

In [152]:
import pandas as pd
import plotly.express as px

def PolyArea(weights):
    x = [tup[0]  for tup in weights]
    y = [tup[1]  for tup in weights]
    return 0.5*np.abs(np.dot(x,np.roll(y,1))-np.dot(y,np.roll(x,1)))

data = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/nn_convergence.csv")
layers = ["conv1.weight", "conv1.bias"]
data = data[data.layer.isin(layers) & (data.description.str.contains('POST'))]
l1 = data[(data.layer==layers[0])].reset_index()
l1["bias"] = data.weight[(data.layer==layers[1])].to_list()
l1["weights"] = list(zip(l1.weight, l1.bias))
vars = ["algorithm_round", "epoch_or_iteration", "description", "layer"]
l1 = l1[vars + ["weights"]]
areas = l1.groupby(["algorithm_round", "epoch_or_iteration", "description", "layer"])['weights'].transform(PolyArea)
areas
# l2 = l1.groupby(["algorithm_round", "epoch_or_iteration", "description", "layer"]).agg(vars=("weights", "PolyArea"))
# l2.head()

# l2 = (l1.set_index(vars)
#          .assign(area=l1.groupby(vars).weights.apply(PolyArea))
#       )
# l2

0       2.284154e-06
1       5.407450e-06
2       1.277336e-05
3       2.284154e-06
4       5.407450e-06
            ...
4497    1.195835e-07
4498    1.195835e-07
4499    1.195835e-07
4500    1.195835e-07
4501    1.195835e-07
Name: weights, Length: 4502, dtype: float64

# Inference

1. Train metric x agente
2. Test metric x agente
3. Max agentes train y test x métrica

In [114]:
import pandas as pd
import plotly.express as px

train = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/nn_train.csv")

metric = "accuracy"
f2 = px.line(train, x="algorithm_round", y=metric, color="agent", title=f"{metric} evolution across rounds by agent")
f2

In [14]:
import pandas as pd
import plotly.express as px

train = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/nn_train.csv")
test = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/nn_inference.csv")

metric = "test_accuracy"
f2 = px.line(test, x="algorithm_round", y=metric, color="agent", title=f"{metric} evolution across rounds by agent")
f2
# import plotly.express as px
# import plotly.graph_objects as go

# fig1 = px.line(df, x='A', y='D')
# fig2 = px.line(df2, x='X', y='Y')

# fig = go.Figure(data = fig1.data + fig2.data)
# fig.show()

# test.rename(columns={"test_accuracy":"accuracy"})
# pd.concat([train, test])
# px.line(train, x="algorithm_round", y="accuracy", color="agent")

In [ ]:
import plotly.graph_objects as go
import numpy as np

train = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/nn_train.csv")
test = pd.read_csv(r"C:/Users/samue/OneDrive/Escritorio/Tareas UNI/tfg/tfg_samuel/vis/xperiments/experimentos_con_cnn/05_non_complete/raw/nn_inference.csv")

g_train = train.groupby(["algorithm_round"]).agg(maximum_accuracy=('accuracy', 'max'),
                                                 minimum_accuracy=('accuracy', 'min'),
                                                 mean_accuracy=('accuracy', 'mean')).reset_index()
g_test = test.groupby(["algorithm_round"]).agg(maximum_accuracy=('test_accuracy', 'max'),
                                                 minimum_accuracy=('test_accuracy', 'min'),
                                                 mean_accuracy=('test_accuracy', 'mean')).reset_index()

x = list(g_test.algorithm_round.unique())
x_rev = x[::-1]

nmax = g_train.maximum_accuracy.to_list()
nmin = g_train.minimum_accuracy.to_list()
nmin = nmin[::-1]

tmax = g_test.maximum_accuracy.to_list()
tmin = g_test.minimum_accuracy.to_list()
tmin = tmin[::-1]


fig = go.Figure()

fig.add_trace(go.Scatter(
    x=x+x_rev,
    y=nmax+nmin,
    fill='toself',
    fillcolor='rgba(0,176,246,0.2)',
    line_color='rgba(255,255,255,0)',
    name='Train',
    showlegend=False,
))
fig.add_trace(go.Scatter(
    x=x+x_rev,
    y=tmax+tmin,
    fill='toself',
    fillcolor='rgba(231,107,243,0.2)',
    line_color='rgba(255,255,255,0)',
    showlegend=False,
    name='Test',
))
fig.add_trace(go.Scatter(
    x=x, y=g_train.mean_accuracy,
    line_color='rgb(0,176,246)',
    name='Train',
))
fig.add_trace(go.Scatter(
    x=x, y=g_test.mean_accuracy,
    line_color='rgb(231,107,243)',
    name='Test',
))

fig.update_traces(mode='lines')
fig.update_layout(title_text="Netowk's performance accuracy by round")
fig.show()

# ANOVA

In [49]:
import os
import re
import pandas as pd
import numpy as np
import scikit_posthocs as sp
from pathlib import Path
import plotly.express as px
import pingouin as pg
import plotly.figure_factory as ff
from statsmodels.multivariate.manova import MANOVA

experiment_variables = ['uuid4',
    'algorithm',
    'algorithm_rounds',
    'consensus_iterations',
    'training_epochs',
    'xmpp_domain',
    'graph_path',
    'dataset',
    'dist',
    'ann',
    'seed',
    'number_of_agents',
    'distribution',
    'network_toplogy']
variables = ["agent", "experiment"]
agent_variables = [
    "minimum_loss_achieved",
    "maximum_accuracy_achieved",
    "maximum_recall_achieved",
    "maximum_precision_achieved",
    "maximum_f1_achieved",
    "mean_seconds_by_round",
]
df = pd.DataFrame(columns=experiment_variables + variables + agent_variables)
# PATH = config.source_path / "experimentos_con_cnn"
PATH = Path(r"C:\Users\samue\OneDrive\Escritorio\Tareas UNI\tfg\tfg_samuel\vis\xperiments\experimentos_con_cnn")
for root, dirs, files in os.walk(PATH):
    if root.endswith("raw"):
        root = Path(root)
        dataset = pd.read_csv(root.joinpath(r"nn_inference.csv"))
        descriptive = root.parent.name
        
        with open(root.joinpath(r"general.log"), encoding='utf-8') as file:
            my_data = file.read()
        line = re.findall(r"Experiment details: <Experiment (.+)>\n", my_data)[0]
        splits = line.split(",")
        splits = dict(map(lambda i: i.strip().split("="), splits))
        experiment_vals = list(splits.values())
        last_vals = root.parent.name.split("_")
        last_vals[0] = int(last_vals[0])
        experiment_vals.extend(last_vals)
        
        times = pd.read_csv(root.joinpath(r"algorithm.csv"))
        agents = dataset.agent.unique()
        for ag in agents:
            agent_times = times[(times.agent == ag + "@localhost")]
            time = agent_times.seconds_to_complete.mean()

            data = dataset[(dataset.agent == ag)]
            numeric = list(
                map(
                    max,
                    [
                        data.test_accuracy,
                        data.test_recall,
                        data.test_precision,
                        data.test_f1_score,
                    ],
                )
            )
            numerics = [data.test_loss.min()] + numeric + [time]
            row = experiment_vals + [ag] + [descriptive] + numerics
            df.loc[len(df)] = row

In [ ]:
from preprocess import clean
a = "network"
b = "distribution"
c = "minimum_loss_achieved"
atable = df.groupby([a, b]).agg(minimum_loss_achieved=(c, "max")).round(2).reset_index()
atable_c = atable.copy()
atable_c.columns = [clean(var) for var in atable_c.columns]
fig = ff.create_table(atable_c)
fig.update_layout(title_text="Table of Minimum Loss achieved grouped by Type and Network")
#fig.update_layout(config["anova"]["f1"]["layout"])
fig.write_image("table_groupby.svg")

WARNING	Thread(Thread-113 (run)) choreographer.utils._tmpfile:_tmpfile.py:clean()- Temporary dictory couldn't be removed manually.

In [43]:
template = "seaborn"
fig = px.scatter(
    atable,
    x=b,
    y='mean_secods_by_round',
    color=a,
    title="Interaction plot: Network and Type",
    template=template,
    labels={
        "x": "Type",
        "response": "Avg Minimum loss achieved",
        "trace": "Network",
    },
).update_traces(mode="lines+markers")
fig.update_layout(title_text="Interaction plot: Network and Type")
#fig.update_layout(config["anova"]["f2"]["layout"])

In [44]:
template = "seaborn"
fig = px.scatter(
    atable,
    x=a,
    y='mean_secods_by_round',
    color=b,
    template=template,
    labels={
        "x": "Type",
        "response": "Avg Minimum loss achieved",
        "trace": "Network",
    },
).update_traces(mode="lines+markers")
fig.update_layout(title_text="Interaction plot: Network and Type")

In [45]:
template = "seaborn"
fig = px.box(
    df,
    x=a,
    y='minimum_loss_achieved',
    color=b,
    points="all",
    template=template,
)
fig.update_layout(title_text="Distribution distribution")
fig

In [35]:
fig4 = px.box(
    df,
    x=b,
    y='mean_seconds_by_round',
    color=a,
    points="all",
    template=template,
)
fig.update_layout(title_text="Ann distribution")
fig4

In [46]:
atable = pg.anova(
    data=df,
    dv='minimum_loss_achieved',
    between=[a, b],
    detailed=True,
).round(4)
fig = ff.create_table(atable)
fig.update_layout(title_text="ANOVA table")

In [17]:
pg_test = pg.pairwise_tukey(
    data=df, dv="maximum_accuracy_achieved", between="distribution"
).round(3)
fig = ff.create_table(pg_test)
fig.update_layout(title_text="Post-hoc Tuckey Test")

In [48]:
options = df.distribution.unique()
array = []
for opt in options:
    opt_values = df.maximum_accuracy_achieved[(df.distribution == opt)]
    array.append(opt_values)
data_nem = np.array(array)
nemtable = sp.posthoc_nemenyi_friedman(data_nem.T).to_numpy()
fig = px.imshow(nemtable, x=options, y=options, color_continuous_scale="Viridis", aspect="auto")
fig.update_traces(text=nemtable, texttemplate="%{text}")
fig.update_xaxes(side="top")
fig.update_layout(title_text="Post-hoc Nemenyi Test")
fig.update_layout(config["anova"]["nemenyi"]["layout"])
fig

In [15]:
manova = MANOVA.from_formula(
    "minimum_loss_achieved + maximum_accuracy_achieved + maximum_recall_achieved + maximum_precision_achieved + maximum_f1_achieved ~ distribution",
    data=df,
)
result = manova.mv_test()
intercept = result.results["Intercept"]["stat"]
intercept.reset_index(inplace=True)
intercept = intercept.rename(columns={"index": "tests"})
fig = ff.create_table(intercept)
fig.update_layout(title_text="MANOVA table Intercept")
fig

In [21]:
manova = MANOVA.from_formula(
    "minimum_loss_achieved + maximum_accuracy_achieved + maximum_recall_achieved + maximum_precision_achieved + maximum_f1_achieved ~ distribution",
    data=df,
)
result = manova.mv_test()
distribution = result.results["distribution"]["stat"]
distribution.reset_index(inplace=True)
distribution = distribution.rename(columns={"index": "tests"})
fig = ff.create_table(distribution.round(3))
fig.update_layout(title_text="MANOVA table Distribution")
fig

In [19]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import networkx as nx
import numpy as np
import numpy.typing as npt
import warnings
from pandas.core.frame import DataFrame
from plotly.graph_objects import Figure
from networkx.classes import Graph
from pandas._libs.tslibs.timestamps import Timestamp
from typing import List, Dict
from config import Config, clean, save_or_print_figures

config = Config()

warnings.filterwarnings("ignore")

metric: str = "test_accuracy"
msg_type: str = "SEND-LAYERS"

messages: DataFrame = pd.read_csv(config.experiment_path / r"message.csv")
inference: DataFrame = pd.read_csv(config.experiment_path / r"nn_inference.csv")

def create_coordinates(
    messages: DataFrame,
) -> List[Dict[str, npt.NDArray[np.float64]]]:
    # CONVERT DATA
    messages_mod: DataFrame = messages.copy()
    messages_mod = messages_mod[
        ["sender", "to"]
    ]  # [(messages_mod.algorithm_round <= 100)
    messages_mod.sender = messages_mod.sender.apply(lambda x: x.split("@")[0])
    messages_mod.to = messages_mod.to.apply(lambda x: x.split("@")[0])

    agents: List[str] = sorted(messages_mod.sender.unique())

    # GENERATE COORDINATES
    cross: DataFrame = pd.crosstab(index=messages_mod.sender, columns=messages_mod.to)
    G: Graph = nx.random_geometric_graph(len(agents), 0)
    G = nx.relabel_nodes(G, {i: a for i, a in enumerate(agents)})
    tuples: DataFrame = cross.stack().reset_index()
    tuples = tuples[tuples[0] > 0]
    tuples = list(tuples.itertuples(index=False))
    G.add_weighted_edges_from(tuples)

    node_x = []
    node_y = []
    for node in G.nodes():
        x, y = G.nodes[node]["pos"]
        node_x.append(x)
        node_y.append(y)

    np.random.seed(2)

    x_dictionary: Dict[str : npt.NDArray[np.float64]] = {
        x: node_x[i] for i, x in enumerate(agents)
    }
    y_dictionary: Dict[str : npt.NDArray[np.float64]] = {
        x: node_y[i] for i, x in enumerate(agents)
    }
    return x_dictionary, y_dictionary


def create_nodes_plot(
    inference: DataFrame,
    x_coords: Dict[str, npt.NDArray[np.float64]],
    y_coords: Dict[str, npt.NDArray[np.float64]],
) -> Figure:
    nodes: DataFrame = inference.copy()
    nodes = nodes[["agent", "timestamp", metric]]

    nodes["timestamp"] = pd.to_datetime(nodes.timestamp)
    nodes["timestamp"] = nodes.timestamp.dt.strftime("%Y/%m/%d %H:%M:%S")
    nodes["timestamp"] = pd.to_datetime(nodes.timestamp)
    first_date: Timestamp = nodes.timestamp.min()
    nodes["timestamp"] = nodes.timestamp.apply(
        lambda x: round((x - first_date) / pd.Timedelta(seconds=1), 2)
    )
    ## CONVERT TO PANEL DATA
    nodes["agent_id"] = nodes.groupby(nodes.columns.tolist(), sort=False).ngroup() + 1
    mux: DataFrame = pd.MultiIndex.from_product(
        [timestamps, np.array(nodes.agent.unique())],
        names=["timestamp", "agent"],
    )

    nodes = nodes.set_index(["timestamp", "agent"]).reindex(mux).reset_index()
    for agent in nodes.agent.unique():
        nodes[nodes.agent == agent] = nodes[nodes.agent == agent].fillna(method="ffill")
    nodes = nodes.fillna(0)

    def set_value(
        row_number: str, assigned_value: Dict[str, List[float]]
    ) -> List[float]:
        return assigned_value[row_number]

    nodes["X"] = nodes["agent"].apply(set_value, args=(x_coords,))
    nodes["Y"] = nodes["agent"].apply(set_value, args=(y_coords,))
    range_color: List[float] = [
        float(nodes[metric].min()),
        float(nodes[metric].max()),
    ]
    nodes["size"] = [35 for x in range(len(nodes))]
    return nodes
    
    
def create_edges_plot(
    messages: DataFrame,
    x_coords: Dict[str, npt.NDArray[np.float64]],
    y_coords: Dict[str, npt.NDArray[np.float64]],
) -> Figure:
    # EDGES DF
    edges: DataFrame = messages.copy()
    edges = edges[["sender", "to", "timestamp", "algorithm_round"]][
        edges.type == msg_type
    ]
    edges[["sender", "domain"]] = edges.sender.str.split("@", expand=True)
    edges[["to", "domain2"]] = edges.to.str.split("@", expand=True)
    edges = edges.drop(["domain", "domain2", "algorithm_round"], axis=1)
    edges["edge"] = list(map(lambda x: tuple(sorted(x)), zip(edges.sender, edges.to)))
    edges["weight"] = edges.groupby(["edge"]).cumcount().add(1)
    edges["timestamp"] = pd.to_datetime(edges.timestamp)
    edges["timestamp"] = edges.timestamp.dt.strftime("%Y/%m/%d %H:%M:%S")
    edges["timestamp"] = pd.to_datetime(edges.timestamp)
    first_date: Timestamp = edges.timestamp.min()
    edges["timestamp"] = edges.timestamp.apply(
        lambda x: round((x - first_date) / pd.Timedelta(seconds=1), 2)
    )

    ## CONVERT TO PANEL DATA
    keep: DataFrame = edges.groupby(["timestamp", "edge"])["timestamp"].idxmax()
    edges: DataFrame = edges.loc[keep]
    mux: DataFrame = pd.MultiIndex.from_product(
        [timestamps, np.array(edges.edge.unique())],
        names=["timestamp", "edge"],
    )
    edges = edges.set_index(["timestamp", "edge"]).reindex(mux).reset_index()
    for agent in edges.edge.unique():
        edges[edges.edge == agent] = edges[edges.edge == agent].fillna(method="ffill")
    edges = edges.fillna(0)

    ## LAST EDGE TRANSFORMATIONS
    def set_value(
        row_number: str, assigned_value: Dict[str, List[float]]
    ) -> List[float]:
        return assigned_value[row_number]

    edges["sender"] = list(map(lambda x: x[0], edges.edge))
    edges["to"] = list(map(lambda x: x[1], edges.edge))
    edges["X_sender"] = edges["sender"].apply(set_value, args=(x_coords,))
    edges["Y_sender"] = edges["sender"].apply(set_value, args=(y_coords,))
    edges["X_to"] = edges["to"].apply(set_value, args=(x_coords,))
    edges["Y_to"] = edges["to"].apply(set_value, args=(y_coords,))
    edges["X"] = list(
        map(lambda x: [x[0], x[1]], list(zip(edges.X_sender, edges.X_to)))
    )
    edges["Y"] = list(
        map(lambda x: [x[0], x[1]], list(zip(edges.Y_sender, edges.Y_to)))
    )
    edges = edges.drop(["sender", "to", "X_sender", "Y_sender", "X_to", "Y_to"], axis=1)
    return edges

In [20]:
XC, YC = create_coordinates(messages)
nodes = create_nodes_plot(inference, XC, YC)
edges = create_edges_plot(messages, XC, YC)
print(len(nodes), len(edges))

4890 9780

In [ ]:
mg = pd.concat([nodes, edges])
mg 
"""
Habría que simplemente recolectar los timestamps únicos de edges y añadirlos a nodes antes de hacer
el refill, y viceversa. De ese modo todos tendrán el msimo número de timestamps y en el zip 
saldrá bien la cosa
"""

,timestamp,agent,test_accuracy,agent_id,X,Y,size,edge,weight
0,0.0,a0,0.2808,1.0,0.474795,0.345572,35.0,NaN,NaN
1,0.0,a1,0.0000,0.0,0.337114,0.083945,35.0,NaN,NaN
2,0.0,a2,0.0000,0.0,0.206107,0.225631,35.0,NaN,NaN
3,0.0,a3,0.0000,0.0,0.93083,0.53506,35.0,NaN,NaN
4,0.0,a4,0.0000,0.0,0.063212,0.445169,35.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
5075,4565.0,NaN,NaN,NaN,"[0.20610721325098713, 0.06321212805444998]","[0.22563088067364456, 0.4451692574337265]",NaN,"(a2, a4)",174.0
5076,4565.0,NaN,NaN,NaN,"[0.930830475558127, 0.06321212805444998]","[0.5350598426651461, 0.4451692574337265]",NaN,"(a3, a4)",183.0
5077,4565.0,NaN,NaN,NaN,"[0.3371140307596322, 0.930830475558127]","[0.08394481785252528, 0.5350598426651461]",NaN,"(a1, a3)",136.0
5078,4565.0,NaN,NaN,NaN,"[0.3371140307596322, 0.06321212805444998]","[0.08394481785252528, 0.4451692574337265]",NaN,"(a1, a4)",155.0
5079,4565.0,NaN,NaN,NaN,"[0.20610721325098713, 0.930830475558127]","[0.22563088067364456, 0.5350598426651461]",NaN,"(a2, a3)",170.0